name: Test and create report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: run test
      run: npm run test
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results-test
        path: ./allure-results
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.17.0 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: run test1
      run: npm run test1
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results-test
        path: ./allure-results
  store_results_and_generate report:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
    - name: Display structure of downloaded files
      run: ls -R
    - name: Unpack artifacts
      if: always()
      run: 7z x allure-results-test ./allure-results && 7z x allure-results-test1 ./allure-results
    - name: Generate allure-report
      if: always()
      run: npm run allure:generate
    - name: Deploy Report
      uses: JamesIves/github-pages-deploy-action@3.1.0
      if: always()
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH: master
        FOLDER: allure-report
        TARGET_FOLDER: docs
    - name: Pushes docs to another repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACCES_TOANOTHER_ACC }}
      with:
        source-directory: 'docs'
        destination-github-username: 'ToActions'
        destination-repository-name: 'HtmlActions'
        user-email: s.fart2012@gmail.com
        target-branch: main
