name: Test and create report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: run test
      run: npm run test
    - name: Create Report
      if: always()
    # trying to save history of previous runs if it is exists
      run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history || true && npm run allure:generate
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-report
        path: ./allure-report
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@3.1.0
      if: always()
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should deploy.
        TARGET_FOLDER: docs
      # If your repo is private and you want upload your report to another repo uncomment and set credential 
    # - name: Pushes to another repository
    #   uses: cpina/github-action-push-to-another-repository@main
    #   if: always()
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
    #   with:
    #     source-directory: 'docs'
    #     destination-github-username: 'UserName'
    #     destination-repository-name: 'RepoName'
    #     user-email: some.email@gmail.com
    #     target-branch: main