name: actionTest

on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO test
    steps:
      - name: Start
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10.x"
      - uses: actions/checkout@v1
      - name: Run Tests
        env:
          SELENIUM_HUB_HOST: "localhost"
        run: npm cit
