name: actionTest

on: [push]

  jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO test
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Start
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: $({ matrix.node-version})
      - uses: actions/checkout@v1
      #- name: Run Tests
      #- run: npm ci
      #- run: npm test
