name: "test my project"
on:
  push:
  pull-request:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: "setup node"
        with:
          node-version: "13.x"
      - uses: actions/checkout@v1
      # - run: node -v
      # - name: "install"
      #   run: npm i

      # - name: "test"
      #   run: npm run test
