name: actionTest

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Setup tests
      - uses: actions/checkout@v1
      - name: Install
        run: npm i

      # - name: "test"
      #   run: npm run test
