name: actionTest

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - uses: actions/checkout@v1
      - run: ls
      - run: npm i
      - run: npm run test
