name: actionTest

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "13.x"
      - uses: actions/checkout@v1
      - name: Read directory
      - run: ls
      - name: Install
      - run: npm install
      - name: Run Tests
      #- run: npm ci
      #- run: npx wdio run wdio.conf.js
