name: wdioTestActions

on:
  push:
    branches: 
      - main

jobs:
  prepair:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: run tests
        run: npm run test
